export const Data = [
  {
    vehicleId: "EV1",
    numberOfTrips: 50,
    tripKilometers: 1000,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.5,
    averageTripsPerDay: 5,
    averageWorkingHours: 8,
    co2Emission: 80,
    vendorName: "Tesla",
  },
  {
    vehicleId: "EV2",
    numberOfTrips: 30,
    tripKilometers: 600,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 3,
    averageTripsPerDay: 3,
    averageWorkingHours: 7,
    co2Emission: 60,
    vendorName: "Nissan",
  },
  {
    vehicleId: "EV3",
    numberOfTrips: 40,
    tripKilometers: 800,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2,
    averageTripsPerDay: 4,
    averageWorkingHours: 7.5,
    co2Emission: 70,
    vendorName: "Chevrolet",
  },
  {
    vehicleId: "EV4",
    numberOfTrips: 45,
    tripKilometers: 900,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.2,
    averageTripsPerDay: 4.5,
    averageWorkingHours: 7.8,
    co2Emission: 75,
    vendorName: "Toyota",
  },
  {
    vehicleId: "EV11",
    numberOfTrips: 35,
    tripKilometers: 700,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.4,
    averageTripsPerDay: 3.5,
    averageWorkingHours: 8.8,
    co2Emission: 65,
    vendorName: "BMW",
  },
  {
    vehicleId: "EV12",
    numberOfTrips: 48,
    tripKilometers: 960,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.7,
    averageTripsPerDay: 4.8,
    averageWorkingHours: 8.5,
    co2Emission: 78,
    vendorName: "Audi",
  },
  {
    vehicleId: "EV13",
    numberOfTrips: 55,
    tripKilometers: 1100,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.9,
    averageTripsPerDay: 5.5,
    averageWorkingHours: 9.2,
    co2Emission: 85,
    vendorName: "Mercedes-Benz",
  },
  {
    vehicleId: "EV14",
    numberOfTrips: 42,
    tripKilometers: 840,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.3,
    averageTripsPerDay: 4.2,
    averageWorkingHours: 8,
    co2Emission: 72,
    vendorName: "Hyundai",
  },
  {
    vehicleId: "EV15",
    numberOfTrips: 38,
    tripKilometers: 760,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.6,
    averageTripsPerDay: 3.8,
    averageWorkingHours: 7.5,
    co2Emission: 70,
    vendorName: "Kia",
  },
  {
    vehicleId: "EV8",
    numberOfTrips: 25,
    tripKilometers: 500,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2,
    averageTripsPerDay: 2.5,
    averageWorkingHours: 7,
    co2Emission: 50,
    vendorName: "Ford",
  },
  {
    vehicleId: "EV9",
    numberOfTrips: 40,
    tripKilometers: 800,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.3,
    averageTripsPerDay: 4,
    averageWorkingHours: 8.3,
    co2Emission: 70,
    vendorName: "Honda",
  },
  {
    vehicleId: "EV10",
    numberOfTrips: 60,
    tripKilometers: 1200,
    averageKilometersPerTrip: 20,
    averageDailyChargingTime: 2.6,
    averageTripsPerDay: 6,
    averageWorkingHours: 9,
    co2Emission: 85,
    vendorName: "Volkswagen",
  },

  // Add more vehicles as needed
];
